CLASSIFICATION_RULES = {
    "aluguel": "Moradia",
    "conta de água|luz|internet": "Contas",
    "netflix|spotify|hbo|disney|streaming": "Serviços de Streaming e Entretenimento",
    "gasolina|abastec\\w*|combustível": "Combustível",
    "maquiagem|creme|beleza": "Beleza e Cuidados Pessoais",
    "tênis|camisa|roupa|vestuário": "Vestuário",
    "multa|estacionamento": "Impostos e Taxas",
    "mcdonald|starbucks|sushi|rodizio|pastel|lanchinho": "Alimentação",
    "bar|cinema|parque|sinuca": "Lazer",
    "shopping|boteco": "Lazer",
    "mercado|feira|supermercado": "Supermercado",
    "farmácia|remédio|vitamina": "Saúde",
    "academia|consulta|medica|dentista": "Saúde",
    "ônibus|táxi|uber|transporte": "Transporte",
    "lotacao": "Transporte",
    "celular|smartphone": "Eletrônicos e Tecnologia",
    "livros": "Cultura e Arte",
    "doa[cç][ãa]o": "Presentes e Doações",
    "ifood": "Delivery"
}